### ISSUE TITLE
Cookbook fails to run on CentOS 5

### ISSUE THREAD

**Issue by tas50** [chef-cookbooks/yum-chef#14]
### Cookbook version
master

### Chef-client version
12.12

### Platform Details
CentOS 5

       [2016-07-23T04:37:31+00:00] ERROR: yum_repository[chef-stable] (yum-chef::default line 21) had an error: Mixlib::ShellOut::ShellCommandFailed: execute[yum-makecache-chef-stable] (/tmp/kitchen/cache/cookbooks/yum/providers/repository.rb line 69) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
       ---- Begin output of yum -q -y makecache --disablerepo=* --enablerepo=chef-stable ----
       STDOUT:
       STDERR: Traceback (most recent call last):
         File "/usr/bin/yum", line 29, in ?
           yummain.user_main(sys.argv[1:], exit_code=True)
         File "/usr/share/yum-cli/yummain.py", line 309, in user_main
           errcode = main(args)
         File "/usr/share/yum-cli/yummain.py", line 178, in main
           result, resultmsgs = base.doCommands()
         File "/usr/share/yum-cli/cli.py", line 349, in doCommands
           return self.yum_cli_commands[self.basecmd].doCommand(self, self.basecmd, self.extcmds)
         File "/usr/share/yum-cli/yumcommands.py", line 502, in doCommand
           repo.repoXML
         File "/usr/lib/python2.4/site-packages/yum/yumRepo.py", line 1399, in <lambda>
           repoXML = property(fget=lambda self: self._getRepoXML(),
         File "/usr/lib/python2.4/site-packages/yum/yumRepo.py", line 1391, in _getRepoXML
           self._loadRepoXML(text=self)
         File "/usr/lib/python2.4/site-packages/yum/yumRepo.py", line 1374, in _loadRepoXML
           return self._groupLoadRepoXML(text)
         File "/usr/lib/python2.4/site-packages/yum/yumRepo.py", line 1365, in _groupLoadRepoXML
           if self._commonLoadRepoXML(text):
         File "/usr/lib/python2.4/site-packages/yum/yumRepo.py", line 1201, in _commonLoadRepoXML
           result = self._getFileRepoXML(local, text)
         File "/usr/lib/python2.4/site-packages/yum/yumRepo.py", line 974, in _getFileRepoXML
           cache=self.http_caching == 'all')
         File "/usr/lib/python2.4/site-packages/yum/yumRepo.py", line 811, in _getFile
           http_headers=headers,
         File "/usr/lib/python2.4/site-packages/urlgrabber/mirror.py", line 412, in urlgrab
           return self._mirror_try(func, url, kw)
         File "/usr/lib/python2.4/site-packages/urlgrabber/mirror.py", line 398, in _mirror_try
           return func_ref( *(fullurl,), **kwargs )
         File "/usr/lib/python2.4/site-packages/urlgrabber/grabber.py", line 936, in urlgrab
           return self._retry(opts, retryfunc, url, filename)
         File "/usr/lib/python2.4/site-packages/urlgrabber/grabber.py", line 854, in _retry
           r = apply(func, (opts,) + args, {})
         File "/usr/lib/python2.4/site-packages/urlgrabber/grabber.py", line 922, in retryfunc
           fo = URLGrabberFileObject(url, filename, opts)
         File "/usr/lib/python2.4/site-packages/urlgrabber/grabber.py", line 1010, in __init__
           self._do_open()
         File "/usr/lib/python2.4/site-packages/urlgrabber/grabber.py", line 1093, in _do_open
           fo, hdr = self._make_request(req, opener)
         File "/usr/lib/python2.4/site-packages/urlgrabber/grabber.py", line 1202, in _make_request
           fo = opener.open(req)
         File "/usr/lib64/python2.4/urllib2.py", line 358, in open
           response = self._open(req, data)
         File "/usr/lib64/python2.4/urllib2.py", line 376, in _open
           '_open', req)
         File "/usr/lib64/python2.4/urllib2.py", line 337, in _call_chain
           result = func(*args)
         File "/usr/lib64/python2.4/site-packages/M2Crypto/m2urllib2.py", line 82, in https_open
           h.request(req.get_method(), req.get_selector(), req.data, headers)
         File "/usr/lib64/python2.4/httplib.py", line 810, in request
           self._send_request(method, url, body, headers)
         File "/usr/lib64/python2.4/httplib.py", line 833, in _send_request
           self.endheaders()
         File "/usr/lib64/python2.4/httplib.py", line 804, in endheaders
           self._send_output()
         File "/usr/lib64/python2.4/httplib.py", line 685, in _send_output
           self.send(msg)
         File "/usr/lib64/python2.4/httplib.py", line 652, in send
           self.connect()
         File "/usr/lib64/python2.4/site-packages/M2Crypto/httpslib.py", line 55, in connect
           sock.connect((self.host, self.port))
         File "/usr/lib64/python2.4/site-packages/M2Crypto/SSL/Connection.py", line 177, in connect
           if not check(self.get_peer_cert(), self.addr[0]):
         File "/usr/lib64/python2.4/site-packages/M2Crypto/SSL/Checker.py", line 88, in __call__
           fieldName='subjectAltName')
       M2Crypto.SSL.Checker.WrongHost: Peer certificate subjectAltName does not match host, expected packages.chef.io, got DNS:*.bintray.com, DNS:bintray.com
       ---- End output of yum -q -y makecache --disablerepo=* --enablerepo=chef-stable ----
       Ran yum -q -y makecache --disablerepo=* --enablerepo=chef-stable returned 1
       [2016-07-23T04:37:32+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

**Comment by tas50** [comment]
@jtimberman Is this something we were expecting with bintray?

**Comment by iennae** [comment]
@tas50 This looks ok as of now:

kitchen converge default-centos-511
-----> Starting Kitchen (v1.8.0)
-----> Creating <default-centos-511>...
       Bringing machine 'default' up with 'virtualbox' provider...
       ==> default: Importing base box 'opscode-centos-5.11'...
==> default: Matching MAC address for NAT networking...
       ==> default: Setting the name of the VM: kitchen-yum-chef-default-centos-511_default_1471755729568_74454
       ==> default: Fixed port collision for 22 => 2222. Now on port 2203.
       ==> default: Clearing any previously set network interfaces...
       ==> default: Preparing network interfaces based on configuration...
           default: Adapter 1: nat
       ==> default: Forwarding ports...
           default: 22 => 2203 (adapter 1)
       ==> default: Booting VM...
       ==> default: Waiting for machine to boot. This may take a few minutes...
           default: SSH address: 127.0.0.1:2203
           default: SSH username: vagrant
           default: SSH auth method: private key
           default: Warning: Connection timeout. Retrying...
           default: Warning: Connection timeout. Retrying...
           default: Warning: Connection timeout. Retrying...
           default:
           default: Vagrant insecure key detected. Vagrant will automatically replace
           default: this with a newly generated keypair for better security.
           default:
           default: Inserting generated public key within guest...
           default: Removing insecure key from the guest if it's present...
           default: Key inserted! Disconnecting and reconnecting using new SSH key...
       ==> default: Machine booted and ready!
       ==> default: Checking for guest additions in VM...
       ==> default: Setting hostname...
       ==> default: Machine not provisioned because `--no-provision` is specified.
       [SSH] Established
       Vagrant instance <default-centos-511> created.
       Finished creating <default-centos-511> (1m11.13s).
-----> Converging <default-centos-511>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 4.2.3...
       Removing non-cookbook files before transfer
       Preparing validation.pem
       Preparing client.rb
-----> Installing Chef Omnibus (install only if missing)
       Downloading https://www.chef.io/chef/install.sh to file /tmp/install.sh
       Trying wget...
       Trying python...
       Download complete.
       el 5 x86_64
       Getting information for chef stable  for el...
       downloading https://omnitruck-direct.chef.io/stable/chef/metadata?v=&p=el&pv=5&m=x86_64
         to file /tmp/install.sh.3551/metadata.txt
       trying wget...
       sha1    	1d32a3284c572921dd41710c87a9b8205862919c
       sha256  	afc8e0f4c60055cf08ab3914c6ae25e183e234e7efcfa81080339e2986a97e0e
       url     	http://chef.bintray.com/stable/el/5/chef-12.13.37-1.el5.x86_64.rpm
       version 	12.13.37
       downloaded metadata file looks valid...
       downloading http://chef.bintray.com/stable/el/5/chef-12.13.37-1.el5.x86_64.rpm
         to file /tmp/install.sh.3551/chef-12.13.37-1.el5.x86_64.rpm
       trying wget...
       Comparing checksum with sha256sum...

       WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING

       You are installing an omnibus package without a version pin.  If you are installing
       on production servers via an automated process this is DANGEROUS and you will
       be upgraded without warning on new releases, even to new major releases.
       Letting the version float is only appropriate in desktop, test, development or
       CI/CD environments.

       WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING

       Installing chef
       installing with rpm...
       warning: /tmp/install.sh.3551/chef-12.13.37-1.el5.x86_64.rpm: Header V3 DSA signature: NOKEY, key ID 83ef826a
       Preparing...                ########################################### [100%]
          1:chef                   ########################################### [100%]
       Thank you for installing Chef!
       Transferring files to <default-centos-511>
       Starting Chef Client, version 12.13.37
       Creating a new client identity for default-centos-511 using the validator key.
       resolving cookbooks for run list: ["yum-chef::default", "test"]
       Synchronizing Cookbooks:
         - yum-chef (1.0.1)
         - test (0.1.0)
         - yum (3.11.0)
       Installing Cookbook Gems:
       Compiling Cookbooks...
       Converging 2 resources
       Recipe: yum-chef::default
         * yum_repository[chef-stable] action create
           * template[/etc/yum.repos.d/chef-stable.repo] action create
             - create new file /etc/yum.repos.d/chef-stable.repo
             - update content in file /etc/yum.repos.d/chef-stable.repo from none to ae9c9f
             --- /etc/yum.repos.d/chef-stable.repo     	2016-08-21 05:04:48.000000000 +0000
             +++ /etc/yum.repos.d/.chef-chef-stable.repo20160821-3666-842wfw   	2016-08-21 05:04:48.000000000 +0000
             @@ -1 +1,12 @@
             +# This file was generated by Chef
             +# Do NOT modify this file by hand.
             +
             +[chef-stable]
             +name=Chef Software Inc chef-stable repository
             +baseurl=https://packages.chef.io/stable-yum/el/5/$basearch
             +enabled=1
             +gpgcheck=1
             +gpgkey=https://downloads.chef.io/packages-chef-io-public.key
             +sslcacert=/etc/pki/tls/certs/ca-bundle.crt
             +sslverify=true
             - change mode from '' to '0644'
             - restore selinux security context
           * execute[yum clean metadata chef-stable] action run
             - execute yum clean metadata --disablerepo=* --enablerepo=chef-stable
           * execute[yum-makecache-chef-stable] action run
             - execute yum -q -y makecache --disablerepo=* --enablerepo=chef-stable
           * ruby_block[yum-cache-reload-chef-stable] action create
             - execute the ruby block yum-cache-reload-chef-stable
           * execute[yum clean metadata chef-stable] action nothing (skipped due to action :nothing)
           * execute[yum-makecache-chef-stable] action nothing (skipped due to action :nothing)
           * ruby_block[yum-cache-reload-chef-stable] action nothing (skipped due to action :nothing)

       Recipe: test::default
         * yum_package[chef-sync] action install
           - install version 1.0.0~rc.7-1.el5 of package chef-sync

       Running handlers:
       Running handlers complete
       Chef Client finished, 6/9 resources updated in 09 minutes 06 seconds
       Finished converging <default-centos-511> (10m47.71s).

I'm closing this up, but if it's still an issue, reopen.
